// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using YALM.Common.Models;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("servicelog")]
	public class ServiceLogDbRecord : ILog
	{
		[Column("serverid"   , IsPrimaryKey = true , PrimaryKeyOrder = 0                        )] public int      Serverid    { get; set; } // integer
		[Column("serviceid"  , IsPrimaryKey = true , PrimaryKeyOrder = 1                        )] public int      Serviceid   { get; set; } // integer
		[Column("interval"                                                                      )] public int      Interval    { get; set; } // integer
		[Column("date"       , IsPrimaryKey = true , PrimaryKeyOrder = 2                        )] public DateTime Date        { get; set; } // timestamp (6) without time zone
		[Column("messagetext", CanBeNull    = false, IsPrimaryKey    = true, PrimaryKeyOrder = 3)] public string   Messagetext { get; set; } = null!; // character varying(1024)

		#region Associations
		/// <summary>
		/// servicelog_serviceid_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(Serviceid), OtherKey = nameof(ServicenameDbRecord.ServiceId))]
		public ServicenameDbRecord Serviceidfkey { get; set; } = null!;
		#endregion
	}
}
