// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("servicestatus")]
	public class ServicestatusDbRecord
	{
		[Column("statusid", IsPrimaryKey = true)] public int     StatusId { get; set; } // integer
		[Column("name"                         )] public string? Name     { get; set; } // character varying(64)

		#region Associations
		/// <summary>
		/// service_statusid_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(StatusId), OtherKey = nameof(ServiceDbRecord.StatusId))]
		public IEnumerable<ServiceDbRecord> Services { get; set; } = null!;
		#endregion
	}
}
