// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("cpu")]
	public class CpuDbRecord
	{
		[Column("serverid"    , IsPrimaryKey = true)] public int     ServerId     { get; set; } // integer
		[Column("name"                             )] public string? Name         { get; set; } // character varying(256)
		[Column("architecture"                     )] public string? Architecture { get; set; } // character varying(256)
		[Column("cores"                            )] public int?    Cores        { get; set; } // integer
		[Column("threads"                          )] public int?    Threads      { get; set; } // integer
		[Column("frequencymhz"                     )] public int?    FrequencyMhz { get; set; } // integer
	}
}
