// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using YALM.API.Models.Db;
using YALM.Common.Models;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("cpulog")]
	public class CpuLogDbRecord : ILog
	{
		[Column("serverid"     , IsPrimaryKey = true, PrimaryKeyOrder = 0)] public int      ServerId      { get; set; } // integer
		[Column("date"         , IsPrimaryKey = true, PrimaryKeyOrder = 1)] public DateTime Date          { get; set; } // timestamp (6) without time zone
		[Column("interval"                                               )] public int      Interval      { get; set; } // integer
		[Column("usage"                                                  )] public double? Usage         { get; set; } // numeric
		[Column("numberoftasks"                                          )] public int?     NumberOfTasks { get; set; } // integer

		public static implicit operator YALM.Common.Models.Graphql.Logs.CpuLog(CpuLogDbRecord log)
		{
			return new YALM.Common.Models.Graphql.Logs.CpuLog
			{
				Date = log.Date,
				Usage = log.Usage,
				NumberOfTasks = log.NumberOfTasks
			};
		}
	}
}
