// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("disk")]
	public class DiskDbRecord
	{
		[Column("id"      , IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     Id       { get; set; } // integer
		[Column("serverid"                                                                                  )] public int     ServerId { get; set; } // integer
		[Column("label"                                                                                     )] public string? Label    { get; set; } // character varying(256)

		#region Associations
		/// <summary>
		/// partition_diskid_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(Id), OtherKey = nameof(PartitionDbRecord.DiskId))]
		public IEnumerable<PartitionDbRecord> Partitions { get; set; } = null!;
		#endregion
	}
}
