// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using YALM.API.Models.Db;
using YALM.Common.Models;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("memorylog")]
	public class MemoryLogDbRecord : ILog
	{
		[Column("serverid"      , IsPrimaryKey = true, PrimaryKeyOrder = 0)] public int      ServerId       { get; set; } // integer
		[Column("date"          , IsPrimaryKey = true, PrimaryKeyOrder = 1)] public DateTime Date           { get; set; } // timestamp (6) without time zone
		[Column("interval"                                                )] public int      Interval       { get; set; } // integer
		[Column("usedkb"                                                  )] public int?     UsedKb         { get; set; } // integer
		[Column("swapusedkb"                                              )] public int?     SwapUsedKb     { get; set; } // integer
		[Column("cachedkb"                                                )] public int?     CachedKb       { get; set; } // integer
		[Column("usedpercentage"                                          )] public decimal? UsedPercentage { get; set; } // numeric(5,4)
	}
}
