// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("memory")]
	public class MemoryDbRecord
	{
		[Column("serverid"   , IsPrimaryKey = true)] public int  ServerId    { get; set; } // integer
		[Column("totalkb"                         )] public int? TotalKb     { get; set; } // integer
		[Column("swaptotalkb"                     )] public int? SwapTotalKb { get; set; } // integer
	}
}
