// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using YALM.API.Models.Db;
using YALM.Common.Models;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("partitionlog")]
	public class PartitionLogDbRecord : ILog
	{
		[Column("diskid"    , IsPrimaryKey = true , PrimaryKeyOrder = 0   , IsIdentity      = true, SkipOnInsert = true, SkipOnUpdate = true)] public int      DiskId     { get; set; } // integer
		[Column("uuid"      , CanBeNull    = false, IsPrimaryKey    = true, PrimaryKeyOrder = 1                                             )] public string   Uuid       { get; set; } = null!; // character varying(64)
		[Column("date"      , IsPrimaryKey = true , PrimaryKeyOrder = 2                                                                     )] public DateTime Date       { get; set; } // timestamp (6) without time zone
		[Column("interval"                                                                                                                  )] public int      Interval   { get; set; } // integer
		[Column("bytestotal"                                                                                                                )] public long?    BytesTotal { get; set; } // bigint
		[Column("usage"                                                                                                                     )] public decimal? Usage      { get; set; } // numeric(3,2)

		#region Associations
		/// <summary>
		/// partitionlog_diskid_uuid_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(DiskId) + "," + nameof(Uuid), OtherKey = nameof(PartitionDbRecord.DiskId) + "," + nameof(PartitionDbRecord.Uuid))]
		public PartitionDbRecord Diskiduuidfkey { get; set; } = null!;
		#endregion
	}
}
