// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;
using YALM.Common.Models.Graphql.OutputModels;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("partition")]
	public class PartitionDbRecord : IConvertible
	{
		[Column("diskid"           , IsPrimaryKey = true , PrimaryKeyOrder = 0   , IsIdentity      = true, SkipOnInsert = true, SkipOnUpdate = true)] public int     DiskId            { get; set; } // integer
		[Column("uuid"             , CanBeNull    = false, IsPrimaryKey    = true, PrimaryKeyOrder = 1                                             )] public string  Uuid              { get; set; } = null!; // character varying(64)
		[Column("filesystemname"                                                                                                                   )] public string? FilesystemName    { get; set; } // character varying(64)
		[Column("filesystemversion"                                                                                                                )] public string? FilesystemVersion { get; set; } // character varying(64)
		[Column("label"                                                                                                                            )] public string? Label             { get; set; } // character varying(256)
		[Column("mountpath"                                                                                                                        )] public string? MountPath         { get; set; } // character varying(1024)

		#region Associations
		/// <summary>
		/// partition_diskid_fkey
		/// </summary>
		[Association(CanBeNull = false, ThisKey = nameof(DiskId), OtherKey = nameof(DiskDbRecord.Id))]
		public DiskDbRecord Diskidfkey { get; set; } = null!;

		/// <summary>
		/// partitionlog_diskid_uuid_fkey backreference
		/// </summary>
		[Association(ThisKey = nameof(DiskId) + "," + nameof(Uuid), OtherKey = nameof(PartitionLogDbRecord.DiskId) + "," + nameof(PartitionLogDbRecord.Uuid))]
		public IEnumerable<PartitionLogDbRecord> Partitionlogs { get; set; } = null!;
		#endregion

		public TypeCode GetTypeCode()
		{
			throw new NotImplementedException();
		}

		public bool ToBoolean(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public byte ToByte(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public char ToChar(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public DateTime ToDateTime(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public decimal ToDecimal(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public double ToDouble(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public short ToInt16(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public int ToInt32(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public long ToInt64(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public sbyte ToSByte(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public float ToSingle(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public string ToString(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public object ToType(Type conversionType, IFormatProvider? provider)
		{
			if (conversionType == typeof(PartitionOutputBase)) 
				return new PartitionOutputBase(Uuid, FilesystemName, FilesystemVersion, Label, MountPath);
			if(conversionType == typeof(PartitionOutput))
				return new PartitionOutputBase(Uuid, FilesystemName, FilesystemVersion, Label, MountPath);
			throw new NotImplementedException();
		}

		public ushort ToUInt16(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public uint ToUInt32(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}

		public ulong ToUInt64(IFormatProvider? provider)
		{
			throw new NotImplementedException();
		}
	}
}
