// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;
using YALM.API.Models.Db;
using YALM.Common.Models;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModel
{
	[Table("programlog")]
	public class ProgramLogDbRecord : ILog
	{
		[Column("serverid"                   )] public int      Serverid                    { get; set; } // integer
		[Column("date"                       )] public DateTime Date                        { get; set; } // timestamp (6) without time zone
		[Column("interval"                   )] public int      Interval                    { get; set; } // integer
		[Column("name"                       )] public string?  Name                        { get; set; } // varchar(255)
		[Column("cpuutilizationpercentage"   )] public decimal? CpuutilizationPercentage    { get; set; } // numeric
		[Column("memoryutilizationpercentage")] public decimal? MemoryUtilizationPercentage { get; set; } // numeric
	}
}
